spring:
  application:
    name: MSYuan-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Redis：刷题签到 BitMap
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msyuan?rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&allowMultiQueries=true
    username: root
    password: 123456
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30 #这里要显示放大
      max-wait: 3000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

      filter:
        stat:
          slow-sql-millis: 1000
          enabled: true
          log-slow-sql: true
          merge-sql: true
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.css,*.ico,*.png,*.jpg,*.gif,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        reset-enable: false
      aop-patterns: com.yuan.msyuanbackend.service.*

  # ===== 第二阶段：Elasticsearch =====
es:
  # 题目索引名
  question-index: question
  sync:
  # 启动时是否全量同步一次
    full-on-startup: false
    # 增量同步每批条数
    batch-size: 500

server:
  address: 0.0.0.0
  port: 8109

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: msyuan
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# application.yml
thread-pool:
  batch-add-question:
    core-size: 20
    max-size: 50
    queue-capacity: 10000
    keep-alive-seconds: 60
    thread-name-prefix: "batch-add-question-"